### ISSUE TITLE
`url` field for the Scpper API

### ISSUE THREAD

**Issue by poupryc** [FiftyNine/ScpperDB#34]
Hi,

I would like to propose an addition to the Scpper API, the addition of a url field indicating the absolute url of the page.

Thanks,

**Comment by FiftyNine** [comment]
I'm assuming you mean page on the wiki (p.e. http://scp-wiki.wikidot.com/scp-1234), not page on the scpper website (http://scpper.com/page/13385759), correct?
I can add either, although API methods already supply the last parts of both URLs (in fields "name" and "id" respectively).

**Comment by poupryc** [comment]
I was obviously talking about the URL of the wiki, actually, sorry if it was unclear.

Actually, name is useful but no field gives the URL of the wiki on which the page was crawled (French wiki, English, Deutsch, Spanish...) for API endpoint like search which could be results in mixed wiki page result.

**Comment by FiftyNine** [comment]
Continuing my life-long quest to be as mildy obstructive as possible I elected to add field "site" instead.
It provides a link to the wiki, which combined with page's name forms full URL.

**Comment by poupryc** [comment]
Thanks !
