### ISSUE TITLE
Username with appended space

### ISSUE THREAD

**Issue by Zokhoi** [FiftyNine/ScpperDB#35]
Hi.

I've noticed that there are wikidot usernames with space appended to it on ScpperDB. The only case I have currently found is etfs95c from FR, but I don't know how many others there are hidden in the database.

![image](https://user-images.githubusercontent.com/20432565/69904687-4dfb2f80-13e4-11ea-9319-eb63d2144f31.png)
notice how the search still matches with an appended space

![image](https://user-images.githubusercontent.com/20432565/69904681-3623ab80-13e4-11ea-96f5-4f3e459bdf8d.png)
and this is a response from the ScpperDB api, retrieved and parsed with [scpper2.js](https://github.com/Joch2520/scpper2.js)

**Comment by FiftyNine** [comment]
Hey, Joch.
I've taken a look at the database, and indeed, there are currently 1321 users with their username ending with a whitespace. I checked wikidot itself and in some cases their names are displayed with a trailing whitespace, and in other cases - without it. I'm not sure what to make of it, Perhaps Wikidot actually allows trailing whitespaces in displayed usernames. Anyway, it's a curiosity, but unless it breaks your workflow in some way, I'm content with leaving everything as it is now.

**Comment by Joch2520** [comment]
[My discord bot project](https://github.com/Joch2520/banhammerlite) verifies a discord user in my server if the wikidot username they provide exactly matches a displayName of a wikidot user on ScpperDB. And for the username input I have trimmed the spaces before and behind it, thus it would never match the displayName with appended space and therefore cause the user to never pass the verification. A fix to this issue would certainly be appreciated.

**Comment by Zokhoi** [comment]
For [my project](https://github.com/scp-cn-tech/fiona) such issue isn't too critical, for I can use trim on the displayName, but this issue would be worth notified of for all who works with ScpperDB in my opinion.
