### ISSUE TITLE
Users who have withdrawn or been banned may be removed from the membership.

### ISSUE THREAD

**Issue by r74tech** [FiftyNine/ScpperDB#37]
This is just an example of mine, so I can't vouch for it.
I was banned in JP last year around January 2020.
I joined JP after that (p.65)  [quickmodule](https://www.wikidot.com/quickmodule.php?module=MemberLookupQModule&q=RTa_technology&s=1971800)
, but I don't think that status is reflected.
I believe that there is no internal flag in Wikidot.
I think that Scpper also knows that you have left, but does not get the information that you have been banned.

Therefore, I think that the participation status of a member who has withdrawn is fixed at null.

If you can fix this, please do so.

**Comment by FiftyNine** [comment]
Crawler wasn't correctly reinstating removed members.
Should be fixed now.
