### ISSUE TITLE
CN pages aren't updated

### ISSUE THREAD

**Issue by Zokhoi** [FiftyNine/ScpperDB#39]
While pages for other branches are not affected, the pages for CN are not updated anymore after 30th May for uncertain reasons.

![image](https://user-images.githubusercontent.com/20432565/123099202-8cdc5480-d464-11eb-84d5-4198bb44715e.png)

The problem seem to be crawling request rate being too fast, as @smlt had experienced on CROM.

![image](https://user-images.githubusercontent.com/20432565/123143503-3fc0a880-d48d-11eb-873a-81215e1bdd7e.png)

**Comment by FiftyNine** [comment]
Should be fixed. For whatever reason serverside code in ajax-module-connector critically failed unless "Referer" header was provided in request. Actual value of the header doesn't seem to matter though, so that's par for the course for wikidot.
