### ISSUE TITLE
[Request] Tags Show Deleted Articles

### ISSUE THREAD

**Issue by 2BoredPlayer** [FiftyNine/ScpperDB#45]
[Search](https://scpper.com/search#:~:text=With-,deleted,-Pages) can show deleted articles, but [Tags](https://scpper.com/tags?tags=8000) do not, so could showing deleted articles on Search be added to Tags as well?

**Comment by 2BoredPlayer** [comment]
Also when I saw the "any" button in [Tags](https://scpper.com/tags?tags=8000), I thought it includes deleted articles but it does not. Maybe include deleted articles in the "any" button?
![Screenshot 2024-03-18 3 22 43 AM](https://github.com/FiftyNine/ScpperDB/assets/119268684/5e723b3d-661a-4173-bed3-d2e5d7583998)

**Comment by FiftyNine** [comment]
Scpper stores deleted pages, but mostly for archival purposes, i.e. for when people are looking for this page specifically whether for moderation or research purposes. Tags page is a discovery tool and should reflect relevant content without unnecessary bloat by deleted articles.

Any/All refers to the combination of tags user entered. As in "Do you want to see pages that have ALL of the tags or ANY one of the tags?'
